title: TaoJunYi
description: webstie.
lang: en
locale: en_GB 
url: "" 
logo: /assets/images/catfish.png 

baseurl: ""
timezone: "Asia/Shanghai"
permalink: :title

highlighter: rouge

plugins:
  # - jekyll-feed
  - jekyll-sitemap
